name: 🆘 Help Wanted
description: Ask for help with using zigantic
title: "[HELP]: "
labels: ["help wanted", "question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Need help with zigantic? 🆘

        We're happy to help! Please provide as much detail as possible so we can assist you effectively.

        **Before asking**, please:
        - [ ] Check the [documentation](https://muhammad-fiaz.github.io/zigantic/)
        - [ ] Search [existing issues](https://github.com/muhammad-fiaz/zigantic/issues) for similar questions
        - [ ] Review the [examples](https://github.com/muhammad-fiaz/zigantic/tree/main/examples)

  - type: dropdown
    id: topic
    attributes:
      label: Help Topic
      description: What area do you need help with?
      options:
        - Installation / Setup
        - Basic usage
        - Validation types
        - JSON parsing
        - Error handling
        - Custom validators
        - Integration with other libraries
        - Performance
        - Best practices
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Zigantic Version
      description: What version of zigantic are you using?
      placeholder: "e.g., 0.0.1"
    validations:
      required: true

  - type: input
    id: zig-version
    attributes:
      label: Zig Version
      description: What version of Zig are you using? (run `zig version`)
      placeholder: "e.g., 0.15.0"
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Question
      description: Describe what you're trying to accomplish and what you need help with.
      placeholder: "I'm trying to... but I'm not sure how to..."
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: If applicable, share the code you're working with.
      render: zig
      placeholder: |
        const z = @import("zigantic");

        // Your code here

  - type: textarea
    id: error
    attributes:
      label: Error or Unexpected Behavior
      description: If you're getting an error or unexpected result, please share it.
      render: shell
      placeholder: Paste any error messages or describe unexpected behavior...

  - type: textarea
    id: tried
    attributes:
      label: What I've Tried
      description: What have you already tried to solve this?
      placeholder: "I've tried... but it didn't work because..."

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful.
      placeholder: Any additional information...

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/muhammad-fiaz/zigantic/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
